import React from "react"
import ICamera from "../loader_package/interface/ICamera"
import IKeyboard from "../loader_package/interface/IKeyboard"
import ILoaded from "../loader_package/interface/ILoaded"
import IModel from "../loader_package/interface/IModel"
import IDummy from "../loader_package/interface/IDummy"
import ISvgMesh from "../loader_package/interface/ISvgMesh"
import IMouse from "../loader_package/interface/IMouse"
import IOrbitCamera from "../loader_package/interface/IOrbitCamera"
import IPrimitive from "../loader_package/interface/IPrimitive"
import ISkybox from "../loader_package/interface/ISkybox"
import ICharacterCamera from "../loader_package/interface/ICharacterCamera"
import IAreaLight from "../loader_package/interface/IAreaLight"
import IPointLight from "../loader_package/interface/IPointLight"
import ISkyLight from "../loader_package/interface/ISkyLight"
import ISpotLight from "../loader_package/interface/ISpotLight"
import IReflector from "../loader_package/interface/IReflector"
import ISprite from "../loader_package/interface/ISprite"
import IAmbientLight from "../loader_package/interface/IAmbientLight"
import IDirectionalLight from "../loader_package/interface/IDirectionalLight"
import ITrigger from "../loader_package/interface/ITrigger"
import ISpawnPoint from "../loader_package/interface/ISpawnPoint"
import IAudio from "../loader_package/interface/IAudio"
import IEnvironment from "../loader_package/interface/IEnvironment"
import IJoystick from "../loader_package/interface/IJoystick"
import IReticle from "../loader_package/interface/IReticle"
import IThirdPersonCamera from "../loader_package/interface/IThirdPersonCamera"
import ISetup from "../loader_package/interface/ISetup"
import IWater from "../loader_package/interface/IWater"

type Children = React.ReactNode



