declare const _default: {
    defaultShadow: boolean;
    defaultLight: string | boolean;
    environment: string | undefined;
    skybox: string | string[] | undefined;
    uiLayer: boolean;
    gridHelper: boolean;
    gridHelperSize: number;
    stats: boolean;
    gravity: number;
    repulsion: number;
    centripetal: boolean;
    antiAlias: boolean | "MSAA" | "SMAA";
    pixelRatio: number;
    fps: number;
    logarithmicDepth: boolean;
    exposure: number;
    shadowResolution: import("../states/useShadowResolution").ShadowResolution;
    shadowDistance: import("../states/useShadowDistance").ShadowDistance;
    pbr: boolean;
    bokehScale: number;
    bloom: boolean;
    bloomIntensity: number;
    bloomThreshold: number;
    bloomRadius: number;
    ssr: boolean;
    ssrIntensity: number;
    ssao: boolean;
    ssaoIntensity: number;
    outlineColor: string;
    outlineHiddenColor: string;
    outlinePattern: string | undefined;
    outlinePulse: number;
    outlineStrength: number;
    bokeh: boolean;
    vignette: boolean;
    texture: string | undefined;
    color: string;
};
export default _default;
