import { MeshStandardMaterial } from "three";
import IStandardMaterialManager from "../../interface/IStandardMaterialManager";
import BasicMaterialManager from "./BasicMaterialManager";
export default class StandardMaterialManager extends BasicMaterialManager<MeshStandardMaterial> implements IStandardMaterialManager {
    static componentName: string;
    static defaults: Partial<import("../../interface/utils/Defaults").default<IStandardMaterialManager>>;
    static schema: Required<import("../../interface/utils/extractProps").ExtractProps<IStandardMaterialManager>>;
    get wireframe(): boolean;
    set wireframe(val: boolean);
    private _envMap?;
    get envMap(): string | undefined;
    set envMap(val: string | undefined);
    get envMapIntensity(): number;
    set envMapIntensity(val: number);
    private _aoMap?;
    get aoMap(): string | undefined;
    set aoMap(val: string | undefined);
    get aoMapIntensity(): number;
    set aoMapIntensity(val: number);
    private _bumpMap?;
    get bumpMap(): string | undefined;
    set bumpMap(val: string | undefined);
    get bumpScale(): number;
    set bumpScale(val: number);
    private _displacementMap?;
    get displacementMap(): string | undefined;
    set displacementMap(val: string | undefined);
    get displacementScale(): number;
    set displacementScale(val: number);
    get displacementBias(): number;
    set displacementBias(val: number);
    get emissiveIntensity(): number;
    set emissiveIntensity(val: number);
    get emissive(): boolean;
    set emissive(val: boolean);
    private _lightMap?;
    get lightMap(): string | undefined;
    set lightMap(val: string | undefined);
    get lightMapIntensity(): number;
    set lightMapIntensity(val: number);
    private _metalnessMap?;
    get metalnessMap(): string | undefined;
    set metalnessMap(val: string | undefined);
    get metalness(): number;
    set metalness(val: number);
    private _roughnessMap?;
    get roughnessMap(): string | undefined;
    set roughnessMap(val: string | undefined);
    get roughness(): number;
    set roughness(val: number);
    private _normalMap?;
    get normalMap(): string | undefined;
    set normalMap(val: string | undefined);
    get normalScale(): number;
    set normalScale(val: number);
}
