import React from "react"
import ICamera from "../package/interface/ICamera"
import IKeyboard from "../package/interface/IKeyboard"
import ILoaded from "../package/interface/ILoaded"
import IModel from "../package/interface/IModel"
import IDummy from "../package/interface/IDummy"
import ISvgMesh from "../package/interface/ISvgMesh"
import IMouse from "../package/interface/IMouse"
import IOrbitCamera from "../package/interface/IOrbitCamera"
import IPrimitive from "../package/interface/IPrimitive"
import ISkybox from "../package/interface/ISkybox"
import ICharacterCamera from "../package/interface/ICharacterCamera"
import IAreaLight from "../package/interface/IAreaLight"
import IPointLight from "../package/interface/IPointLight"
import ISkyLight from "../package/interface/ISkyLight"
import ISpotLight from "../package/interface/ISpotLight"
import IReflector from "../package/interface/IReflector"
import ISprite from "../package/interface/ISprite"
import IAmbientLight from "../package/interface/IAmbientLight"
import IDirectionalLight from "../package/interface/IDirectionalLight"
import ITrigger from "../package/interface/ITrigger"
import ISpawnPoint from "../package/interface/ISpawnPoint"
import IAudio from "../package/interface/IAudio"
import IEnvironment from "../package/interface/IEnvironment"
import IJoystick from "../package/interface/IJoystick"
import IReticle from "../package/interface/IReticle"
import IThirdPersonCamera from "../package/interface/IThirdPersonCamera"
import ISetup from "../package/interface/ISetup"
import IWater from "../package/interface/IWater"

type Children = React.ReactNode



