export declare const WIDTH = 375;
export declare const HEIGHT = 667;
export declare const MONITOR_INTERVAL = 100;
export declare const SEC2FRAME = 60;
export declare const FRAME2SEC: number;
export declare const MIN_POLAR_ANGLE = 10;
export declare const MAX_POLAR_ANGLE = 175;
export declare const ORTHOGRAPHIC_FRUSTUM = 5.7;
export declare const NEAR = 0.1;
export declare const FAR = 1000;
export declare const SHADOW_BIAS = -0.0055;
export declare const DUMMY_URL = "https://unpkg.com/lingo3d-dummy@1.0.4/assets/";
export declare const YBOT_URL: string;
export declare const TEXTURES_URL = "https://unpkg.com/lingo3d-textures@1.0.4/assets/";
export declare const WATERNORMALS_URL: string;
export declare const FACADE_URL = "https://unpkg.com/lingo3d-facade@1.0.0/assets/";
export declare const FOREST_URL = "https://unpkg.com/lingo3d-forest@1.0.0/assets/";
export declare const EDITOR_URL = "https://unpkg.com/lingo3d-editor@1.0.5/assets/";
export declare const WASM_URL = "https://unpkg.com/lingo3d-wasm@1.0.1/assets/";
export declare const DEBUG = false;
export declare const VERSION = "2.0.3";
export declare const FRAME_WIDTH = 12;
export declare const FRAME_HEIGHT: number;
export declare const FRAME_MAX: number;
export declare const APPBAR_HEIGHT = 28;
export declare const PANELS_HEIGHT = 200;
export declare const CONTEXT_MENU_ITEM_HEIGHT = 25;
