import { Point3d } from "@lincode/math";
import { Object3D } from "three";
import { Cancellable } from "@lincode/promiselikes";
import { LingoMouseEvent } from "../../../interface/IMouse";
import IStaticObjectManager from "../../../interface/IStaticObjectManager";
import MeshItem from "../MeshItem";
import "./raycast";
import Appendable from "../../../api/core/Appendable";
export declare const idMap: Map<string, Set<StaticObjectManager<Object3D<import("three").Event>>>>;
export declare const getMeshItemSets: (id: string | Array<string> | MeshItem) => Set<MeshItem>[];
export default class StaticObjectManager<T extends Object3D = Object3D> extends Appendable<T> implements IStaticObjectManager {
    dispose(): this;
    protected _id?: string;
    get id(): string | undefined;
    set id(val: string | undefined);
    protected addToRaycastSet(set: Set<Object3D>): Cancellable;
    private _onClick?;
    get onClick(): ((e: LingoMouseEvent) => void) | undefined;
    set onClick(cb: ((e: LingoMouseEvent) => void) | undefined);
    private _onMouseDown?;
    get onMouseDown(): ((e: LingoMouseEvent) => void) | undefined;
    set onMouseDown(cb: ((e: LingoMouseEvent) => void) | undefined);
    private _onMouseUp?;
    get onMouseUp(): ((e: LingoMouseEvent) => void) | undefined;
    set onMouseUp(cb: ((e: LingoMouseEvent) => void) | undefined);
    private _onMouseOver?;
    get onMouseOver(): ((e: LingoMouseEvent) => void) | undefined;
    set onMouseOver(cb: ((e: LingoMouseEvent) => void) | undefined);
    private _onMouseOut?;
    get onMouseOut(): ((e: LingoMouseEvent) => void) | undefined;
    set onMouseOut(cb: ((e: LingoMouseEvent) => void) | undefined);
    private _onMouseMove?;
    get onMouseMove(): ((e: LingoMouseEvent) => void) | undefined;
    set onMouseMove(cb: ((e: LingoMouseEvent) => void) | undefined);
    get name(): string;
    set name(val: string);
    protected getRay(): import("three").Ray;
    pointAt(distance: number): Point3d;
    rayIntersectsAt(target: StaticObjectManager, maxDistance?: number): Point3d | undefined;
    rayIntersects(target: StaticObjectManager): boolean;
    intersects(target: StaticObjectManager): boolean;
    get clientX(): number;
    get clientY(): number;
    get frustumVisible(): boolean;
    lookAt(target: MeshItem | Point3d): void;
    lookAt(x: number, y: number | undefined, z: number): void;
    onLookToEnd: (() => void) | undefined;
    lookTo(target: MeshItem | Point3d, alpha: number, a: any, targetQuaternion?: any): void;
    lookTo(x: number, y: number | undefined, z: number, alpha: number, targetQuaternion?: any): void;
    getWorldPosition(): Point3d;
}
