import { PositionalAudio } from "three";
import PositionedItem from "../api/core/PositionedItem";
import IAudio from "../interface/IAudio";
export default class Audio extends PositionedItem<PositionalAudio> implements IAudio {
    static componentName: string;
    static defaults: Partial<import("../interface/utils/Defaults").default<IAudio>>;
    static schema: Required<import("../interface/utils/extractProps").ExtractProps<IAudio>>;
    constructor();
    dispose(): this;
    play(): void;
    pause(): void;
    stop(): void;
    private srcState;
    get src(): string | undefined;
    set src(val: string | undefined);
    private autoplayState;
    get autoplay(): boolean;
    set autoplay(val: boolean);
    private pausedState;
    get paused(): boolean;
    set paused(val: boolean);
    private stoppedState;
    get stopped(): boolean;
    set stopped(val: boolean);
    get loop(): boolean;
    set loop(val: boolean);
    get volume(): number;
    set volume(val: number);
    get playbackRate(): number;
    set playbackRate(val: number);
    get distance(): number;
    set distance(val: number);
    get distanceModel(): string;
    set distanceModel(val: string);
    get maxDistance(): number;
    set maxDistance(val: number);
    get rolloffFactor(): number;
    set rolloffFactor(val: number);
}
